/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cappu_launcherwin_nativejni_KookNativeCalendar */

#ifndef _Included_com_cappu_launcherwin_nativejni_KookNativeCalendar
#define _Included_com_cappu_launcherwin_nativejni_KookNativeCalendar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeCalendar
 * Method:    getJiYear
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeCalendar_getJiYear
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeCalendar
 * Method:    getJiMonth
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeCalendar_getJiMonth
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeCalendar
 * Method:    getJiDay
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeCalendar_getJiDay
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
