/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cappu_launcherwin_nativejni_KookNativeChannel */

#ifndef _Included_com_cappu_launcherwin_nativejni_KookNativeChannel
#define _Included_com_cappu_launcherwin_nativejni_KookNativeChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeChannel
 * Method:    CappuChannel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeChannel_CappuChannel
  (JNIEnv *, jclass);

/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeChannel
 * Method:    CappuChannelNet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeChannel_CappuChannelNet
  (JNIEnv *, jclass);

/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeChannel
 * Method:    KLTChannel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeChannel_KLTChannel
  (JNIEnv *, jclass);

/*
 * Class:     com_cappu_launcherwin_nativejni_KookNativeChannel
 * Method:    Replace
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cappu_launcherwin_nativejni_KookNativeChannel_Replace
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
